// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEllpHBhhDbTdvhNo38k8-VC8fqamEeCE',
    appId: '1:59299231378:web:8d15fb57bb11ef10b7184b',
    messagingSenderId: '59299231378',
    projectId: 'food-expiry-tracker-f2a2c',
    authDomain: 'food-expiry-tracker-f2a2c.firebaseapp.com',
    databaseURL: 'https://food-expiry-tracker-f2a2c-default-rtdb.firebaseio.com',
    storageBucket: 'food-expiry-tracker-f2a2c.firebasestorage.app',
    measurementId: 'G-PGPNJQNDYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQw-bs66i04JbcRhvhXiiRA74DeuVf1UU',
    appId: '1:59299231378:android:e5fb9e998a66b5cfb7184b',
    messagingSenderId: '59299231378',
    projectId: 'food-expiry-tracker-f2a2c',
    databaseURL: 'https://food-expiry-tracker-f2a2c-default-rtdb.firebaseio.com',
    storageBucket: 'food-expiry-tracker-f2a2c.firebasestorage.app',
  );
}
